### ISSUE TITLE
Build failed on fee issue in wallet.py

### ISSUE THREAD

**Issue by Christewart** [drivechain-project/bitcoin#16]
### Describe the issue

https://travis-ci.org/drivechain-project/bitcoin/jobs/248532545

It looks we like we have some sort of rounding error inside of wallet.py. I'm not sure if this is a change we have introduced or a bug upstream. If it is a problem upstream we need to report it eventually.

**Comment by CryptAxe** [comment]
It looks like this was fixed in https://github.com/drivechain-project/bitcoin/pull/15 by properly surrounding the wallet code which I added in 
``` #ifdef WALLET_ENABLED ``` blocks. 

Since https://github.com/drivechain-project/bitcoin/pull/13 is passing on Travis CI now, I think we can close this issue. I didn't touch any Python code, so it must have been a bitcoind compilation issue in the test runner or something? I'm not really familiar with the Python part of the testing system but nothing else really makes sense as a reason that the C++ code made the Python tests fail like that.
