### ISSUE TITLE
Tie the sidechain keys to individual Sidechain

### ISSUE THREAD

**Issue by ghabs** [drivechain-project/bitcoin#53]
Currently the sidechain private key is a hardcoded constant that is shared among all three valid sidechains. https://github.com/drivechain-project/bitcoin/blob/mainchainBMM/src/sidechain.h#L18

My understanding of the [hashrate escrow bip](https://github.com/drivechain-project/docs/blob/master/bip1-hashrate-escrow.md) is that each sidechain will have its own CTIP, where each new Sidechain when soft forked in will have a unique private key derived from the version number.

Proposed Changes:
- ValidSidechains array stores the key info per sidechain
- CreateSidechainDeposit() and CreateWTPrimePayout() are refactored to use it per sidechain

**Comment by psztorc** [comment]
You are correct. But one other thing that we're trying to do (but haven't had time) is just remove the need for OP_CheckSig completely. Because the signature takes up space but doesn't really do anything.

However, we still use that setup, for convenience -- it hooks into all of the explorer/wallet systems that tell everyone how much BTC is """in""" an address.

Ideally, there would be a UX-friendly way to send "to" a sidechain address (or something similar), but in a way that doesn't really need a private key at all (although the public key could still be a hash of the 0.1 sidechain binary, to avoid disputes over that).

Perhaps the best thing would be to abandon the "sidechain address" concept, and refer to everything by sidechain number (nSidechain), and have the UX window display the CTIP. That would also solve this issue.

**Comment by CryptAxe** [comment]
Also related: https://github.com/drivechain-project/bitcoin/issues/36

**Comment by ghabs** [comment]
Closing as resolved in https://github.com/drivechain-project/bitcoin/pull/59
